### ISSUE TITLE
Run Angularytics only in production environment

### ISSUE THREAD

**Issue by robertochingon** [mgonto/angularytics#37]
Hi,

  I have integrated Angularytics in my AngularJS web app. It´s working fine. But, I have three environments (development, test and production), so Angularytics is gathering analytics from both of them. I just would like to run it in production environment.

I don´t find a proper way to do it. I have an ENVIRONMENT constant with different values according to the environment, in order to do something like:

if ($rootScope.ENVIRONMENT == 'Production') {    
		    var head = document.getElementsByTagName('head')[0];
		    var js = document.createElement("script");    
		    js.type = "text/javascript";
		    js.src =   "lib/plugins/angularytics-yanpy.js";
		    head.appendChild(js);

where lib/plugins/angularytics-yanpy.js is:

(function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
(i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
})(window,document,'script','//www.google-analytics.com/analytics.js','ga');
		
ga('create', 'UA-59702007-1', 'auto');

I guess this will work in production, however in development I´m getting this error because Angularytics script is looking for ga.

ReferenceError: ga is not defined
    at Object.a.trackPageView (http://localhost/lib/plugins/angularytics.min.js:8:1406)
    at http://localhost/lib/plugins/angularytics.min.js:8:710
    at http://localhost/lib/plugins/angularytics.min.js:8:543
    at Array.forEach (native)
    at Object.forEach (http://localhost/lib/angular/angular.js:130:11)
    at $get.g (http://localhost/lib/plugins/angularytics.min.js:8:521)
    at Object.$get.h.trackPageView (http://localhost/lib/plugins/angularytics.min.js:8:691)
    at http://localhost/lib/plugins/angularytics.min.js:8:751
    at Object.$get.Scope.$broadcast (http://localhost/lib/angular/angular.js:8307:28)
    at afterLocationChange (http://localhost/lib/angular/angular.js:5649:18)

Any suggestions?

**Comment by robertochingon** [comment]
Update: As workaround, I have got the NOT minified angularytics.js script and inside its code I would like to insert the environment condition, like:

(function () {
  angular.module('angularytics', []).provider('Angularytics', function () {
  	if($rootScope.ENVIRONMENT == 'Production') {
    var eventHandlersNames = ['Google'];
 ...

But, this is a complex javascript for my skills and I don´t know how to include $rootScope. I always got it undefined.

Please, help!

**Comment by rudijs** [comment]
You could use a simpler approach...

For example during the config phase in your Angular app check the current URL for local, dev, production:

    .config(function(AngularyticsProvider) {
      var angularyticsEventHandlers = [];
      if (window.location.href.match(/local/)) {
        angularyticsEventHandlers.push('Console');
      }
      else {
        angularyticsEventHandlers.push('GoogleUniversal');
      };
      AngularyticsProvider.setEventHandlers(angularyticsEventHandlers);
    }).run(function(Angularytics) {
      Angularytics.init();
    });

**Comment by tennisgent** [comment]
+1 for @rudijs's answer

**Comment by mgonto** [comment]
Thanks @rudijs for answering. That's exactly the best approach ):.
